//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJs_With_Web_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class callcenterEntities : DbContext
    {
        public callcenterEntities()
            : base("name=callcenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public DbSet<userinfo> userinfoes { get; set; }
    
        public virtual int uspAddUser(string pLogin, string pPassword, string pName, string pEmail, Nullable<bool> pIsAdmin, Nullable<bool> pIsActive, Nullable<bool> pCanEdit, Nullable<bool> pCanFilter, ObjectParameter responseMessage)
        {
            var pLoginParameter = pLogin != null ?
                new ObjectParameter("pLogin", pLogin) :
                new ObjectParameter("pLogin", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            var pNameParameter = pName != null ?
                new ObjectParameter("pName", pName) :
                new ObjectParameter("pName", typeof(string));
    
            var pEmailParameter = pEmail != null ?
                new ObjectParameter("pEmail", pEmail) :
                new ObjectParameter("pEmail", typeof(string));
    
            var pIsAdminParameter = pIsAdmin.HasValue ?
                new ObjectParameter("pIsAdmin", pIsAdmin) :
                new ObjectParameter("pIsAdmin", typeof(bool));
    
            var pIsActiveParameter = pIsActive.HasValue ?
                new ObjectParameter("pIsActive", pIsActive) :
                new ObjectParameter("pIsActive", typeof(bool));
    
            var pCanEditParameter = pCanEdit.HasValue ?
                new ObjectParameter("pCanEdit", pCanEdit) :
                new ObjectParameter("pCanEdit", typeof(bool));
    
            var pCanFilterParameter = pCanFilter.HasValue ?
                new ObjectParameter("pCanFilter", pCanFilter) :
                new ObjectParameter("pCanFilter", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspAddUser", pLoginParameter, pPasswordParameter, pNameParameter, pEmailParameter, pIsAdminParameter, pIsActiveParameter, pCanEditParameter, pCanFilterParameter, responseMessage);
        }
    
        public virtual int uspDeleteUser(string pLogin, ObjectParameter responseMessage)
        {
            var pLoginParameter = pLogin != null ?
                new ObjectParameter("pLogin", pLogin) :
                new ObjectParameter("pLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteUser", pLoginParameter, responseMessage);
        }
    
        public virtual int uspMakeUserAdmin(string pLogin, ObjectParameter responseMessage)
        {
            var pLoginParameter = pLogin != null ?
                new ObjectParameter("pLogin", pLogin) :
                new ObjectParameter("pLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspMakeUserAdmin", pLoginParameter, responseMessage);
        }
    
        public virtual int uspMakeUserNonAdmin(string pLogin, ObjectParameter responseMessage)
        {
            var pLoginParameter = pLogin != null ?
                new ObjectParameter("pLogin", pLogin) :
                new ObjectParameter("pLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspMakeUserNonAdmin", pLoginParameter, responseMessage);
        }
    
        public virtual int uspUnDeleteUser(string pLogin, ObjectParameter responseMessage)
        {
            var pLoginParameter = pLogin != null ?
                new ObjectParameter("pLogin", pLogin) :
                new ObjectParameter("pLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUnDeleteUser", pLoginParameter, responseMessage);
        }
    
        public virtual int uspValidateUser(string pLogin, string pPassword, ObjectParameter responseMessage)
        {
            var pLoginParameter = pLogin != null ?
                new ObjectParameter("pLogin", pLogin) :
                new ObjectParameter("pLogin", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspValidateUser", pLoginParameter, pPasswordParameter, responseMessage);
        }
    }
}
