//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJs_With_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public byte[] PasswordHash { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public System.Guid Salt { get; set; }
        public bool IsActive { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanFilter { get; set; }
    }
}
